# Generated by Django 3.2.8 on 2021-11-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='projectObjetive',
            new_name='projectObjective',
        ),
    ]
