# Generated by Django 4.0.3 on 2022-04-23 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_venta_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_manager.factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
