# Generated by Django 4.0.3 on 2022-04-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0003_venta_factura_alter_cliente_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
    ]
